### ISSUE TITLE
I don't know how to use the this view

### ISSUE THREAD

**Issue by ahuynh359** [idleray/TableView#2]
Hi, Can you update your readme how to use this view? I think it's awesome.

**Comment by idleray** [comment]
There is a sample app:
[https://github.com/idleray/TableView/blob/master/app/src/main/java/com/rayject/tableview/MainActivity.java](https://github.com/idleray/TableView/blob/master/app/src/main/java/com/rayject/tableview/MainActivity.java)
I will update README later.
